// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lldtlysejtyvbbxmdfyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsZHRseXNlanR5dmJieG1kZnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzQ3NTYsImV4cCI6MjA2MzUxMDc1Nn0.EagjF9ElGMU0i0fOxVOFKw74HODotKwFlFzJNawhk90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);